# Generated by Django 2.1.5 on 2019-03-12 23:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mission', models.TextField()),
                ('type', models.IntegerField(choices=[(1, 'fundacja'), (2, 'organizacja pozarządowoa')])),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('post_code', models.CharField(max_length=6)),
                ('phone', models.CharField(max_length=20)),
                ('helped_times', models.IntegerField(default=0)),
                ('received_bags', models.IntegerField(default=0)),
                ('password_reset_code', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_bags', models.IntegerField(default=0)),
                ('helped_orgs', models.IntegerField(default=0)),
                ('organised_collections', models.IntegerField(default=0)),
                ('street', models.CharField(max_length=255, null=True)),
                ('city', models.CharField(max_length=255, null=True)),
                ('post_code', models.CharField(max_length=6, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('password_reset_code', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
