# Generated by Django 2.1.5 on 2019-03-13 00:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Oddam_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=255)),
                ('goal', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('description', models.TextField()),
                ('picture', models.FileField(upload_to='')),
                ('who_organised', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CollectionArticles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=255)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Oddam_app.Collection')),
            ],
        ),
        migrations.CreateModel(
            name='GlobalStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numb_of_bags', models.IntegerField()),
                ('helped_orgs', models.IntegerField()),
                ('organised_collections', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OrganisationArticles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=255)),
                ('organisation', models.ManyToManyField(to='Oddam_app.OrganisationDetails')),
            ],
        ),
        migrations.CreateModel(
            name='OrganisationBeneficiaries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=255)),
                ('organisation', models.ManyToManyField(to='Oddam_app.OrganisationDetails')),
            ],
        ),
    ]
